import { useState } from "react";
import { motion } from "motion/react";
import { Activity, Ambulance, ArrowDownRight, ArrowUpRight, Clock3, Flame, Radio, Search, ShieldCheck, Siren, TrendingDown, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { Input } from "@/components/ui/input";
import { demoResponders } from "@/lib/rescuegrid-data";
import { useRescueGridStore } from "@/lib/rescuegrid-store";
import type { AppView } from "@/lib/rescuegrid-types";
import { cn } from "@/lib/utils";
import { CommandScene } from "./command-scene";
import { IncidentCard } from "./incident-card";
import { IncidentDetail } from "./incident-detail";
import { StatusBadge } from "./status-badge";

const responseData = [{ time: "00", incidents: 5, response: 4.2 }, { time: "04", incidents: 3, response: 3.8 }, { time: "08", incidents: 12, response: 4.7 }, { time: "12", incidents: 9, response: 3.6 }, { time: "16", incidents: 15, response: 4.1 }, { time: "20", incidents: 8, response: 3.4 }, { time: "24", incidents: 4, response: 3.2 }];
const categoryData = [{ name: "Medical", value: 42 }, { name: "Security", value: 29 }, { name: "Hazard", value: 18 }, { name: "Fire", value: 11 }];

export function AdminDashboard({ view }: { view: AppView }) {
  if (view === "analytics") return <AnalyticsView />;
  if (view === "history") return <HistoryView />;
  return <CommandDashboard />;
}

function CommandDashboard() {
  const incidents = useRescueGridStore((state) => state.incidents);
  const selectedId = useRescueGridStore((state) => state.selectedIncidentId);
  const selectIncident = useRescueGridStore((state) => state.selectIncident);
  const selected = incidents.find((item) => item.id === selectedId) ?? incidents[0];
  const active = incidents.filter((item) => item.status !== "Resolved");
  return <div className="mx-auto max-w-[1800px] p-4 md:p-6">
    <div className="mb-5 flex flex-col justify-between gap-3 lg:flex-row lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-signal">Unified command · Campus sector 01</p><h1 className="mt-2 font-display text-3xl font-bold md:text-4xl">Emergency operations</h1><p className="mt-1 text-sm text-muted-foreground">Live operational picture across all campus response units.</p></div><div className="flex items-center gap-3 font-mono text-[10px] text-muted-foreground"><span>LAST SYNC 05:39:42</span><span className="size-2 rounded-full bg-success animate-pulse" /></div></div>
    <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Siren} label="Active incidents" value={String(active.length).padStart(2, "0")} trend="+2 this hour" alert /><Metric icon={Clock3} label="Avg response" value="3:42" trend="18% faster" /><Metric icon={Users} label="Units available" value="08" trend="of 12 online" /><Metric icon={ShieldCheck} label="Campus readiness" value="94%" trend="Optimal" /></div>
    <div className="grid min-h-[690px] gap-4 xl:grid-cols-[20rem_minmax(34rem,1fr)_23rem]">
      <section className="glass-panel rounded-lg p-3"><div className="flex items-center justify-between px-1 pb-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Incident stream</p><p className="mt-1 font-mono text-[9px] text-success">LIVE · {active.length} ACTIVE</p></div><Radio className="size-4 text-signal animate-pulse" /></div><div className="space-y-2">{incidents.map((incident) => <IncidentCard key={incident.id} incident={incident} selected={selected?.id === incident.id} onSelect={() => selectIncident(incident.id)} />)}</div></section>
      <section className="relative min-h-[32rem] overflow-hidden rounded-lg border border-border bg-panel shadow-command"><CommandScene /><div className="pointer-events-none absolute inset-0 bg-map-vignette" /><div className="absolute left-4 top-4 flex items-center gap-2 rounded-md border border-border bg-background/75 px-3 py-2 backdrop-blur-xl"><Activity className="size-4 text-signal" /><div><p className="font-mono text-[9px] uppercase text-muted-foreground">Live campus telemetry</p><p className="text-xs font-semibold">4 incidents · 12 units</p></div></div><div className="absolute bottom-4 left-4 right-4 grid grid-cols-3 gap-2"><MapLegend color="bg-alert" label="Critical" count="02" /><MapLegend color="bg-signal" label="Responding" count="03" /><MapLegend color="bg-success" label="Available" count="08" /></div></section>
      {selected ? <IncidentDetail incident={selected} mode="admin" /> : <div className="glass-panel grid place-items-center rounded-lg text-sm text-muted-foreground">Select an incident</div>}
    </div>
    <section className="mt-4 glass-panel rounded-lg p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Response units</p><p className="mt-1 text-sm font-semibold">Team availability</p></div><span className="font-mono text-[10px] text-success">8 / 12 READY</span></div><div className="grid gap-2 md:grid-cols-3 xl:grid-cols-5">{demoResponders.map((responder) => <div key={responder.id} className="flex items-center gap-3 rounded-md border border-border bg-background/30 p-3"><div className="grid size-9 place-items-center rounded bg-secondary font-mono text-xs font-bold">{responder.initials}</div><div className="min-w-0"><p className="truncate text-xs font-semibold">{responder.name}</p><p className="mt-0.5 font-mono text-[9px] text-muted-foreground">{responder.unit} · {responder.eta}</p></div><span className={cn("ml-auto size-2 shrink-0 rounded-full", responder.status === "Available" ? "bg-success" : responder.status === "Offline" ? "bg-muted-foreground" : "bg-signal animate-pulse")} /></div>)}</div></section>
  </div>;
}

function Metric({ icon: Icon, label, value, trend, alert }: { icon: typeof Activity; label: string; value: string; trend: string; alert?: boolean }) { return <motion.div whileHover={{ y: -2 }} className="glass-panel rounded-md p-4"><div className="flex items-start justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className={cn("mt-2 font-display text-3xl font-bold", alert && "text-alert")}>{value}</p></div><div className={cn("grid size-9 place-items-center rounded-md", alert ? "bg-alert/10 text-alert" : "bg-signal/10 text-signal")}><Icon className="size-4" /></div></div><p className={cn("mt-3 flex items-center gap-1 text-[10px]", trend.includes("faster") || trend === "Optimal" ? "text-success" : "text-muted-foreground")}>{trend.includes("faster") ? <TrendingDown className="size-3" /> : <ArrowUpRight className="size-3" />}{trend}</p></motion.div>; }
function MapLegend({ color, label, count }: { color: string; label: string; count: string }) { return <div className="rounded-md border border-border bg-background/80 p-2.5 backdrop-blur-xl"><p className="flex items-center gap-1.5 font-mono text-[9px] uppercase text-muted-foreground"><span className={cn("size-1.5 rounded-full", color)} />{label}</p><p className="mt-1 font-mono text-lg font-bold">{count}</p></div>; }

function AnalyticsView() { return <div className="mx-auto max-w-7xl p-4 md:p-8"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-signal">Operational intelligence</p><h1 className="mt-2 font-display text-3xl font-bold md:text-4xl">Response analytics</h1><p className="mt-2 text-sm text-muted-foreground">A rolling 30-day view of campus incidents and team performance.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Metric icon={Clock3} label="Median dispatch" value="01:08" trend="12% faster" /><Metric icon={Ambulance} label="Resolution rate" value="96.4%" trend="Optimal" /><Metric icon={Flame} label="High priority" value="18" trend="-7% vs prior" /></div><div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]"><ChartCard title="Incident volume" subtitle="Reports by hour"><ResponsiveContainer width="100%" height={280}><AreaChart data={responseData}><defs><linearGradient id="areaSignal" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--signal)" stopOpacity={0.5}/><stop offset="100%" stopColor="var(--signal)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="time" stroke="var(--muted-foreground)" fontSize={10}/><YAxis stroke="var(--muted-foreground)" fontSize={10}/><ChartTooltip contentStyle={{ background: "var(--panel-elevated)", border: "1px solid var(--border)", borderRadius: 6 }}/><Area type="monotone" dataKey="incidents" stroke="var(--signal)" fill="url(#areaSignal)" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Incident mix" subtitle="Category distribution"><ResponsiveContainer width="100%" height={280}><BarChart data={categoryData} layout="vertical"><CartesianGrid stroke="var(--border)" horizontal={false}/><XAxis type="number" stroke="var(--muted-foreground)" fontSize={10}/><YAxis type="category" dataKey="name" width={62} stroke="var(--muted-foreground)" fontSize={10}/><ChartTooltip contentStyle={{ background: "var(--panel-elevated)", border: "1px solid var(--border)", borderRadius: 6 }}/><Bar dataKey="value" fill="var(--alert)" radius={[0, 3, 3, 0]}/></BarChart></ResponsiveContainer></ChartCard></div></div>; }
function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="glass-panel rounded-lg p-4 md:p-5"><div className="mb-5"><p className="font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{subtitle}</p></div>{children}</section>; }

function HistoryView() { const incidents = useRescueGridStore((state) => state.incidents); const [query, setQuery] = useState(""); const filtered = incidents.filter((item) => `${item.id} ${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())); return <div className="mx-auto max-w-7xl p-4 md:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-signal">Incident archive</p><h1 className="mt-2 font-display text-3xl font-bold">Response history</h1></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, location, incident…" className="bg-panel pl-9" /></div></div><div className="mt-6 overflow-x-auto rounded-lg border border-border bg-panel/70"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-border bg-background/30 font-mono text-[9px] uppercase tracking-wider text-muted-foreground"><th className="p-4">Incident</th><th className="p-4">Location</th><th className="p-4">Priority</th><th className="p-4">Status</th><th className="p-4">Responder</th><th className="p-4">Response</th></tr></thead><tbody>{filtered.map((incident) => <tr key={incident.id} className="border-b border-border/70 text-xs last:border-0 hover:bg-accent/40"><td className="p-4"><p className="font-semibold">{incident.title}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{incident.id}</p></td><td className="p-4 text-muted-foreground">{incident.location}</td><td className="p-4"><StatusBadge status={incident.priority} /></td><td className="p-4"><StatusBadge status={incident.status} /></td><td className="p-4">{incident.assignedResponder ?? "—"}</td><td className="p-4 font-mono">{incident.elapsed}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-12 text-center"><Search className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 text-sm font-semibold">No incidents found</p><p className="mt-1 text-xs text-muted-foreground">Try another report ID or campus location.</p></div>}</div></div>; }